#!/usr/bin/env python3

#follow https://iancoleman.io/bip39/ patern

#bytes.fromhex(seedS)

import getpass
import sys

import argparse
from library import *

coins = ['bitcoin','bitcoin-testnet','ethereum']

parser = argparse.ArgumentParser(description='Generate hd wallet and account for bitcoin and ethereum')
#parser.add_argument("--mnemonic", help="generate a new mnemonic seed and output it in the commandline")
#parser.add_argument("--account", help="generate an account from a seed, an account number and a network")
parser.add_argument("--new", help="generate a new mnemonic or account")
args = parser.parse_args()

def print_mnemonic():
    mnemo = create_mnemonic()
    print("Your 24 mnemonic words are: \n" + mnemo[0] + "\n")
    print("The equivalent master seed is: \n" + mnemo[1].hex() + "\n")

def print_account(words,network,account_number):
    seed = create_seed(words)
    if network not in coins:
        sys.exit("Wrong Network : should be ethereum or bitcoin or bitcoin-testnet!")
    
    if network == "bitcoin":
        data = gen_bitcoin_wallet(seed,account_number)
        print("private key : " + data[0].hex() + "\n")
        print("WIF : " + data[1] + "\n")
        print("public key : " + data[2].hex() + "\n")
        print("address : " + data[3] + "\n")                        
    if network == "bitcoin-testnet":
        data = gen_bitcoin_testnet_wallet(seed,account_number)
        print("private key : " + data[0].hex() + "\n")
        print("WIF : " + data[1] + "\n")
        print("public key : " + data[2].hex() + "\n")
        print("address : " + data[3] + "\n")                        

    if network == "ethereum":
        data = gen_ethereum_wallet(seed,account_number)
        print("private key : " + data[0].hex() + "\n")
        print("address : " + data[1] + "\n")                        


if args.new=="mnemonic":
    print_mnemonic()

elif args.new=="account":
    network = input("Please enter network (bitcoin, bitcoin-testnet or ethereum) :")
    if network not in coins:
        sys.exit("Wrong Network : should be ethereum or bitcoin or bitcoin-testnet!")
    number = int(input("Please enter account number :"))
    words = input('Please input 24 mnemonic words :\n')
    print("\n ********** Account Data ********** \n")
    print_account(words,network,number)


